FROM centos/python-38-centos7:latest
USER root
COPY . /python-test-calculator
WORKDIR /python-test-calculator
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN ["pytest", "-v", "--junitxml=reports/result-rh7.xml"]
CMD tail -f /dev/null
