FROM centos/python-38-centos7
COPY . /python-test-calculator
WORKDIR /python-test-calculator
RUN python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt
RUN ["pytest", "-v", "--junit   xml=reports/result.xml"]
CMD tail -f /dev/null
